# Generated by Django 3.2.4 on 2021-07-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
