# Generated by Django 3.2.4 on 2021-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opapp', '0002_alter_meeting_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
